### ISSUE TITLE
[Bug]: Flags can be submitted before and after the event

### ISSUE THREAD

**Issue by Sanielia** [Hack4Krak/Hack4KrakSite#601]
### Description

Basically while tasks endpoint are wrapped with event middleware `disallow_before_event`, flags endpoints aren't. As for frontend there isn't any check if event started or ended.

### Steps to reproduce

To check after the event:

1. Run backend and frontend on latest master
2. Create user and team for team
3. Login as this user
4. Go to localhost:3000/panel and submit flag `hack4KrakCTF{skibdi}`

To check before the event:

1. Replace TasksTemplate/config/event.yaml with this code:

```yaml
# TasksTemplate configuration

# Unique identifier for the event
id: tasks-template
# Date and time when CTF starts (users have access to tasks etc.)
start-date: 2025-06-15T8:30:00+01:00
# After this date users can't upload more flags
end-date: 2025-06-15T15:30:00+01:00
```

2. Do everything from after the event section
